#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# mm — Mattermost CLI with auto-refreshing SSO tokens
#
# A drop-in wrapper around mmctl that automatically refreshes your session
# token from Chrome's cookie store. No passwords, no PATs, no manual steps.
#
# Usage:
#   mm setup                  First-time setup (interactive)
#   mm status                 Show auth status, token age, server info
#   mm refresh                Force-refresh the token from Chrome
#   mm <any mmctl command>    Auto-refresh + passthrough to mmctl
#
# Examples:
#   mm team list --json
#   mm post list myteam:general --json --show-ids -n 100
#   mm channel list myteam --json
#
# Config: ~/.config/mm/
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config paths ─────────────────────────────────────────────────────────────
CONFIG_DIR="${HOME}/.config/mm"
CONFIG_FILE="${CONFIG_DIR}/config"
TOKEN_FILE="${CONFIG_DIR}/token"
VENV_DIR="${CONFIG_DIR}/.venv"
MM_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REFRESH_SCRIPT="${MM_SCRIPT_DIR}/refresh-token.py"
TOKEN_MAX_AGE_SECONDS=3600  # refresh if older than 1 hour

# ── Colors & formatting ─────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  BLUE='\033[0;34m'
  BOLD='\033[1m'
  DIM='\033[2m'
  RESET='\033[0m'
else
  RED='' GREEN='' YELLOW='' BLUE='' BOLD='' DIM='' RESET=''
fi

info()  { echo -e "${BLUE}▸${RESET} $*"; }
ok()    { echo -e "${GREEN}✓${RESET} $*"; }
warn()  { echo -e "${YELLOW}!${RESET} $*" >&2; }
fail()  { echo -e "${RED}✗${RESET} $*" >&2; }
hint()  { echo -e "  ${DIM}$*${RESET}" >&2; }

# ── Helpers ──────────────────────────────────────────────────────────────────

find_mmctl() {
  if command -v mmctl >/dev/null 2>&1; then
    command -v mmctl
  elif [[ -x "${HOME}/bin/mmctl" ]]; then
    echo "${HOME}/bin/mmctl"
  else
    return 1
  fi
}

load_config() {
  MM_URL=""
  MM_AUTH_NAME=""
  if [[ -f "$CONFIG_FILE" ]]; then
    # Safe parsing: only read expected key=value lines, never source arbitrary code
    while IFS='=' read -r key value; do
      # Strip surrounding quotes from value
      value="${value%\"}"
      value="${value#\"}"
      case "$key" in
        MM_URL)       MM_URL="$value" ;;
        MM_AUTH_NAME) MM_AUTH_NAME="$value" ;;
      esac
    done < <(grep -E '^(MM_URL|MM_AUTH_NAME)=' "$CONFIG_FILE")
  fi
}

save_config() {
  mkdir -p "$CONFIG_DIR"
  chmod 700 "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# mm configuration — generated by mm setup
MM_URL="${MM_URL}"
MM_AUTH_NAME="${MM_AUTH_NAME}"
EOF
  chmod 600 "$CONFIG_FILE"
}

token_age_seconds() {
  if [[ ! -f "$TOKEN_FILE" ]]; then
    echo "999999"
    return
  fi
  if [[ "$(uname -s)" == "Darwin" ]]; then
    echo $(( $(date +%s) - $(stat -f %m "$TOKEN_FILE") ))
  else
    echo $(( $(date +%s) - $(stat -c %Y "$TOKEN_FILE") ))
  fi
}

token_age_human() {
  local age=$1
  if (( age < 60 )); then
    echo "${age}s ago"
  elif (( age < 3600 )); then
    echo "$(( age / 60 ))m ago"
  elif (( age < 86400 )); then
    echo "$(( age / 3600 ))h ago"
  else
    echo "$(( age / 86400 ))d ago"
  fi
}

ensure_venv() {
  if [[ -f "${VENV_DIR}/bin/python3" ]] && "${VENV_DIR}/bin/python3" -c "import pycookiecheat" 2>/dev/null; then
    return 0
  fi

  info "Setting up Python environment (one-time) ..."

  # Try uv first (fast), fall back to python3 -m venv + pip
  if command -v uv >/dev/null 2>&1; then
    uv venv "$VENV_DIR" --quiet 2>/dev/null
    uv pip install --python "${VENV_DIR}/bin/python3" pycookiecheat --quiet 2>/dev/null
  elif command -v python3 >/dev/null 2>&1; then
    python3 -m venv "$VENV_DIR" 2>/dev/null
    "${VENV_DIR}/bin/pip" install --quiet pycookiecheat 2>/dev/null
  else
    fail "Python 3 is required but not found."
    hint "Install it: brew install python3"
    return 1
  fi

  if ! "${VENV_DIR}/bin/python3" -c "import pycookiecheat" 2>/dev/null; then
    fail "Failed to install pycookiecheat."
    hint "Try manually: ${VENV_DIR}/bin/pip install pycookiecheat"
    return 1
  fi

  ok "Python environment ready."
}

# ── Token refresh ────────────────────────────────────────────────────────────

do_refresh() {
  local force="${1:-false}"

  load_config
  if [[ -z "$MM_URL" ]]; then
    fail "Not configured yet."
    hint "Run: mm setup"
    return 1
  fi

  # Skip if token is fresh (unless forced)
  if [[ "$force" != "true" && -s "$TOKEN_FILE" ]]; then
    local age
    age=$(token_age_seconds)
    if (( age < TOKEN_MAX_AGE_SECONDS )); then
      return 0
    fi
  fi

  ensure_venv || return 1

  if [[ ! -f "$REFRESH_SCRIPT" ]]; then
    fail "refresh-token.py not found at: $REFRESH_SCRIPT"
    hint "Re-clone the mmctl-setup repo or check your installation."
    return 1
  fi

  local output
  output=$("${VENV_DIR}/bin/python3" "$REFRESH_SCRIPT" --url "$MM_URL" 2>&1) || {
    local exit_code=$?

    # Parse the error to give actionable guidance
    if echo "$output" | grep -qi "MMAUTHTOKEN not found"; then
      echo "" >&2
      fail "No active Mattermost session found in Chrome."
      echo "" >&2
      echo -e "  ${BOLD}To fix this:${RESET}" >&2
      echo -e "  1. Open ${BLUE}${MM_URL}${RESET} in Google Chrome" >&2
      echo -e "  2. Log in via SSO (if prompted)" >&2
      echo -e "  3. Wait for the Mattermost UI to fully load" >&2
      echo -e "  4. Come back here and run: ${BOLD}mm refresh${RESET}" >&2
      echo "" >&2
    elif echo "$output" | grep -qi "could not read"; then
      echo "" >&2
      fail "Cannot read Chrome's cookie store."
      echo "" >&2
      echo -e "  ${BOLD}Common causes:${RESET}" >&2
      echo -e "  • Chrome is not installed" >&2
      echo -e "  • Chrome has never been opened (no cookie database yet)" >&2
      echo -e "  • macOS Keychain denied access — look for a system prompt" >&2
      echo -e "    asking to allow access to \"Chrome Safe Storage\"" >&2
      echo -e "    and click ${BOLD}Always Allow${RESET}" >&2
      echo "" >&2
    else
      fail "Token refresh failed."
      # Only show lines that don't contain potential token data
      echo "$output" | grep -i "ERROR\|error\|failed\|not found\|denied" | sed 's/^/  /' >&2
      hint "Run with MM_DEBUG=1 mm refresh for full output."
    fi

    return $exit_code
  }

  # Show the success line from the Python script
  echo "$output" | grep -i "refreshed" | sed "s/^/$(printf "${GREEN}✓${RESET} ")/" || true
}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_setup() {
  echo ""
  echo -e "${BOLD}mm setup${RESET} — configure Mattermost CLI with auto-refreshing SSO tokens"
  echo ""

  # 1. Check mmctl
  info "Checking for mmctl ..."
  local mmctl_path
  if mmctl_path=$(find_mmctl); then
    ok "Found mmctl at ${mmctl_path}"
    hint "$("$mmctl_path" version 2>/dev/null | head -1 || echo 'unknown version')"
  else
    fail "mmctl is not installed."
    echo ""
    echo -e "  ${BOLD}Install it:${RESET}"
    echo -e "  • Homebrew:  ${BOLD}brew install mmctl${RESET}"
    echo -e "  • Direct:    Download from ${BLUE}https://releases.mattermost.com/mmctl/\${VERSION}/\${PLATFORM}_\${ARCH}.tar${RESET}"
    echo -e "               Supported: darwin_arm64, darwin_amd64, linux_amd64, linux_arm64"
    echo -e "  • Note:      The old github.com/mattermost/mmctl repo is ${RED}archived${RESET}."
    echo ""
    echo -e "  After installing, run ${BOLD}mm setup${RESET} again."
    return 1
  fi

  # 2. Check Python
  info "Checking for Python 3 ..."
  if command -v python3 >/dev/null 2>&1; then
    ok "Found $(python3 --version 2>&1)"
  else
    fail "Python 3 is required for auto token refresh."
    hint "Install it: brew install python3"
    return 1
  fi

  # 3. Check Chrome
  info "Checking for Chrome ..."
  local chrome_cookie_db="${HOME}/Library/Application Support/Google/Chrome/Default/Cookies"
  if [[ "$(uname -s)" == "Darwin" ]]; then
    if [[ -f "$chrome_cookie_db" ]]; then
      ok "Chrome cookie database found."
    elif [[ -d "/Applications/Google Chrome.app" ]]; then
      warn "Chrome is installed but no cookie database found."
      hint "Open Chrome and browse to any site once, then re-run setup."
      return 1
    else
      fail "Google Chrome is not installed."
      hint "Download from https://www.google.com/chrome/"
      return 1
    fi
  else
    # Linux: Chrome cookies are in ~/.config/google-chrome/Default/Cookies
    local linux_cookie_db="${HOME}/.config/google-chrome/Default/Cookies"
    if [[ -f "$linux_cookie_db" ]]; then
      ok "Chrome cookie database found."
    else
      warn "Chrome cookie database not found. Make sure Chrome is installed and has been opened."
    fi
  fi

  # 4. Ask for server URL
  echo ""
  load_config
  local default_url="${MM_URL:-}"
  if [[ -n "$default_url" ]]; then
    read -rp "$(echo -e "${BLUE}▸${RESET}") Mattermost server URL [${default_url}]: " input_url
    MM_URL="${input_url:-$default_url}"
  else
    read -rp "$(echo -e "${BLUE}▸${RESET}") Mattermost server URL: " MM_URL
  fi

  if [[ -z "$MM_URL" ]]; then
    fail "Server URL is required."
    return 1
  fi
  # Normalize: strip trailing slash
  MM_URL="${MM_URL%/}"

  # 5. Auth name
  local default_name="${MM_AUTH_NAME:-work}"
  read -rp "$(echo -e "${BLUE}▸${RESET}") Auth name (nickname for this server) [${default_name}]: " input_name
  MM_AUTH_NAME="${input_name:-$default_name}"

  # 6. Save config
  save_config
  ok "Config saved to ${CONFIG_FILE}"

  # 7. Set up Python venv
  ensure_venv || return 1

  # 8. Try token refresh
  echo ""
  info "Attempting to read your Mattermost session from Chrome ..."
  hint "If macOS asks for Keychain access to \"Chrome Safe Storage\", click Always Allow."
  echo ""

  if do_refresh true; then
    # 9. Set up mmctl auth
    info "Configuring mmctl auth ..."
    if "$mmctl_path" auth login "$MM_URL" \
        --name "$MM_AUTH_NAME" \
        --access-token-file "$TOKEN_FILE" 2>/dev/null; then
      ok "mmctl auth configured as \"${MM_AUTH_NAME}\""
    else
      warn "mmctl auth login had an issue — you may need to run it manually:"
      hint "$mmctl_path auth login $MM_URL --name $MM_AUTH_NAME --access-token-file $TOKEN_FILE"
    fi

    # 10. Verify
    echo ""
    info "Verifying connection ..."
    if "$mmctl_path" team list --suppress-warnings 2>/dev/null; then
      echo ""
      ok "Setup complete! You can now use ${BOLD}mm${RESET} as a drop-in replacement for mmctl."
      echo ""
      echo -e "  ${BOLD}Try it:${RESET}"
      echo -e "    mm team list --json"
      echo -e "    mm channel list <team> --json"
      echo -e "    mm post list <channel-id> --json --show-ids -n 50"
      echo ""
    else
      warn "Connection test failed — token might be expired."
      hint "Open ${MM_URL} in Chrome, log in, and run: mm refresh"
    fi
  else
    echo ""
    warn "Could not read token from Chrome. Make sure you're logged into Mattermost in Chrome."
    hint "After logging in, run: mm refresh"
  fi
}

cmd_status() {
  load_config

  echo ""
  echo -e "${BOLD}mm status${RESET}"
  echo ""

  # Server
  if [[ -n "${MM_URL:-}" ]]; then
    echo -e "  Server:     ${BLUE}${MM_URL}${RESET}"
    echo -e "  Auth name:  ${MM_AUTH_NAME:-not set}"
  else
    echo -e "  Server:     ${DIM}not configured${RESET}"
    hint "Run: mm setup"
    echo ""
    return
  fi

  # mmctl
  local mmctl_path
  if mmctl_path=$(find_mmctl); then
    local ver
    ver=$("$mmctl_path" version 2>/dev/null | grep "^Version:" | awk '{print $2}' | head -1 || echo "unknown")
    echo -e "  mmctl:      ${GREEN}${mmctl_path}${RESET} (v${ver})"
  else
    echo -e "  mmctl:      ${RED}not found${RESET}"
  fi

  # Token
  if [[ -s "$TOKEN_FILE" ]]; then
    local age
    age=$(token_age_seconds)
    local age_str
    age_str=$(token_age_human "$age")
    local token_len
    token_len=$(wc -c < "$TOKEN_FILE" | tr -d ' ')
    if (( age < TOKEN_MAX_AGE_SECONDS )); then
      echo -e "  Token:      ${GREEN}valid${RESET} (${token_len} chars, refreshed ${age_str})"
    else
      echo -e "  Token:      ${YELLOW}stale${RESET} (${token_len} chars, refreshed ${age_str})"
      hint "Will auto-refresh on next command, or run: mm refresh"
    fi
  else
    echo -e "  Token:      ${RED}missing${RESET}"
    hint "Run: mm refresh"
  fi

  # Python venv
  if [[ -f "${VENV_DIR}/bin/python3" ]] && "${VENV_DIR}/bin/python3" -c "import pycookiecheat" 2>/dev/null; then
    echo -e "  Auto-refresh: ${GREEN}ready${RESET} (pycookiecheat installed)"
  else
    echo -e "  Auto-refresh: ${YELLOW}not set up${RESET}"
    hint "Run: mm setup"
  fi

  # Live auth test
  if [[ -n "${mmctl_path:-}" && -s "$TOKEN_FILE" ]]; then
    if "$mmctl_path" auth current --suppress-warnings >/dev/null 2>&1; then
      echo -e "  Connection: ${GREEN}authenticated${RESET}"
    else
      echo -e "  Connection: ${RED}not authenticated${RESET}"
      hint "Token may be expired. Run: mm refresh"
    fi
  fi

  echo ""
}

cmd_refresh() {
  load_config
  if [[ -z "${MM_URL:-}" ]]; then
    fail "Not configured yet."
    hint "Run: mm setup"
    return 1
  fi
  info "Refreshing token from Chrome ..."
  do_refresh true
}

cmd_help() {
  echo ""
  echo -e "${BOLD}mm${RESET} — Mattermost CLI with auto-refreshing SSO tokens"
  echo ""
  echo -e "${BOLD}COMMANDS${RESET}"
  echo "  mm setup                  First-time setup (interactive)"
  echo "  mm status                 Show auth status, token age, server info"
  echo "  mm refresh                Force-refresh the token from Chrome"
  echo "  mm help                   Show this help"
  echo "  mm <any mmctl command>    Auto-refresh + passthrough to mmctl"
  echo ""
  echo -e "${BOLD}EXAMPLES${RESET}"
  echo "  mm team list --json"
  echo "  mm post list myteam:general --json --show-ids -n 100"
  echo "  mm channel list myteam --json"
  echo "  mm user search john.doe --json"
  echo "  mm post list <channel-id> --json --since 2026-04-10T00:00:00Z"
  echo ""
  echo -e "${BOLD}HOW IT WORKS${RESET}"
  echo "  mm reads your Mattermost session token directly from Chrome's"
  echo "  encrypted cookie store on disk (via pycookiecheat). As long as"
  echo "  you have an active Mattermost session in Chrome, mm handles"
  echo "  token refresh automatically — no passwords, no PATs."
  echo ""
  echo -e "${BOLD}WHEN IT BREAKS${RESET}"
  echo "  If you get auth errors, just open your Mattermost server in"
  echo "  Chrome, let SSO log you in, then run: mm refresh"
  echo ""
  echo -e "${BOLD}CONFIG${RESET}"
  echo "  ~/.config/mm/config       Server URL + auth name"
  echo "  ~/.config/mm/token        Session token (auto-managed)"
  echo "  ~/.config/mm/.venv/       Python venv (auto-managed)"
  echo ""
}

# ── Main dispatch ────────────────────────────────────────────────────────────

main() {
  case "${1:-}" in
    setup)
      cmd_setup
      ;;
    status)
      cmd_status
      ;;
    refresh)
      cmd_refresh
      ;;
    help|--help|-h|"")
      cmd_help
      ;;
    *)
      # Passthrough to mmctl with auto-refresh
      load_config

      if [[ -z "${MM_URL:-}" ]]; then
        fail "Not configured yet."
        hint "Run: mm setup"
        exit 1
      fi

      local mmctl_path
      if ! mmctl_path=$(find_mmctl); then
        fail "mmctl is not installed."
        hint "Run: mm setup"
        exit 1
      fi

      # Auto-refresh (fully silent in passthrough mode)
      do_refresh false >/dev/null 2>&1 || {
        warn "Token refresh failed — trying with existing token."
      }

      exec "$mmctl_path" "$@"
      ;;
  esac
}

main "$@"
